#!/usr/bin/env python3
"""
Write ny/data/app/tompkins-legislature-members.json from the scraper's output.

The shape is the fleet's single-county roster shape, unchanged: top level keyed
by DISTRICT, each district holding a `members` list and its `seats` count, with
one `board` key beside them carrying what belongs to the body rather than to a
person (Illinois's Grundy, Coles, Knox and eleven more are the same file). A
Tompkins district elects one legislator, so every list has one member; the
`seats` key is still written, because a card that reads a list length has no way
to say a seat is unfilled.

FLOORS, AND WHY THEY ARE FLOORS. The seat count is EXACT at 16 — the county
elects one legislator per district and that number cannot move between censuses
— while the contact fields are floors below today's measurement, because a
member leaving moves them by ones. Today's run: 16 names, 16 e-mails, 9 personal
telephones, 13 profile links, 41 committee rows, a Chair and a Vice Chair.
check_roster_retention.py is what watches the actual coverage against the
shipped file; these floors only stop a broken parse from shipping.

WHAT IS NOT HERE. No home address (the county's contact sheet prints one for
every member; the scraper drops them by construction). No telephone for the
seven members whose printed number is the Legislature's own switchboard — that
number ships once under `board`, which is where it is true.

Usage:
    python3 ny/scripts/build_tompkins_legislature_roster.py --in <scraper json>
"""
import argparse
import datetime
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
INSTANCE = os.path.dirname(HERE)
ROOT = os.path.dirname(INSTANCE)
OUT_PATH = os.path.join(INSTANCE, "data", "app", "tompkins-legislature-members.json")

SEATS = 16
MIN_EMAILS = 14
MIN_PHONES = 6
MIN_PROFILE_LINKS = 10
MIN_COMMITTEE_ROWS = 30
REQUIRED_ROLES = ("Chair", "Vice Chair")


def main(argv):
    ap = argparse.ArgumentParser(description="Build Tompkins County's legislature roster file.")
    ap.add_argument("--in", dest="src", required=True)
    args = ap.parse_args(argv)

    with open(args.src, encoding="utf-8") as fh:
        doc = json.load(fh)
    members = doc["members"]
    office = doc.get("office") or {}

    problems = []
    if sorted(int(k) for k in members) != list(range(1, SEATS + 1)):
        problems.append("the scrape carries districts %s, not 1..%d"
                        % (sorted(int(k) for k in members), SEATS))
    named = [m for m in members.values() if (m.get("name") or "").strip()]
    if len(named) != SEATS:
        problems.append("%d of %d districts name a legislator" % (len(named), SEATS))
    emails = sum(1 for m in members.values() if m.get("email"))
    phones = sum(1 for m in members.values() if m.get("phone"))
    links = sum(1 for m in members.values() if m.get("profileUrl"))
    committee_rows = sum(len(m.get("committees") or []) for m in members.values())
    if emails < MIN_EMAILS:
        problems.append("%d e-mail(s), floor %d" % (emails, MIN_EMAILS))
    if phones < MIN_PHONES:
        problems.append("%d personal telephone(s), floor %d" % (phones, MIN_PHONES))
    if links < MIN_PROFILE_LINKS:
        problems.append("%d profile link(s), floor %d" % (links, MIN_PROFILE_LINKS))
    if committee_rows < MIN_COMMITTEE_ROWS:
        problems.append("%d committee row(s), floor %d" % (committee_rows, MIN_COMMITTEE_ROWS))
    roles = sorted({m.get("role") for m in members.values() if m.get("role")})
    for role in REQUIRED_ROLES:
        if role not in roles:
            problems.append("no %s is named — the county's contact sheet publishes one, so an "
                            "absence here is a parse failure rather than a vacancy" % role)
    for key in ("lines", "phone", "fax"):
        if not office.get(key):
            problems.append("the Legislature's own office has no %s" % key)
    if not doc.get("term"):
        problems.append("the roster page's term sentence did not parse")

    if problems:
        for p in problems:
            print("build-tompkins-legislature-roster: FAIL %s" % p, file=sys.stderr)
        return 1

    out = {
        "_about": ("GENERATED by ny/scripts/build_tompkins_legislature_roster.py from "
                   "ny/scripts/tompkins_legislature_scraper.py. People from the county's own "
                   "Legislature page and its own contact sheet, joined BY DISTRICT NUMBER; the "
                   "district layer's Member column is read only as a drift witness and never "
                   "shipped. No home address ships, and a telephone equal to the Legislature's "
                   "switchboard is carried under `board` rather than against a member."),
        "board": {
            "address": ", ".join(office["lines"]),
            "phone": office["phone"],
            "fax": office["fax"],
            "term": doc["term"],
            "sourceUrl": doc["sources"]["roster"],
            "contactsUrl": doc["sources"]["contacts"],
            "asOf": datetime.date.today().isoformat(),
        },
    }
    for num in range(1, SEATS + 1):
        m = members[str(num)]
        person = {"name": m["name"], "party": m["party"], "email": m["email"],
                  "committees": m.get("committees") or []}
        if m.get("phone"):
            person["phone"] = m["phone"]
        if m.get("profileUrl"):
            person["url"] = m["profileUrl"]
        if m.get("role"):
            person["role"] = m["role"]
        out[str(num)] = {"members": [person], "seats": 1}

    with open(OUT_PATH, "w", encoding="utf-8") as fh:
        json.dump(out, fh, indent=1, ensure_ascii=False, sort_keys=False)
        fh.write("\n")
    print("build-tompkins-legislature-roster: OK %d districts, %d e-mails, %d personal telephones, "
          "%d profile links, %d committee rows, roles %s -> %s (%d bytes)" %
          (SEATS, emails, phones, links, committee_rows, roles,
           os.path.relpath(OUT_PATH, ROOT), os.path.getsize(OUT_PATH)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
