#!/usr/bin/env python3
"""
/feedback.html — the "report a bug or leave a comment" form for every page
that is not a map app. GENERATED on the same shell as /about.html and
/privacy.html.

WHY IT EXISTS. The six apps carry this form in a dialog, and nothing else on
the site did: a reader on a county board page, a question page or the front
door who found a wrong name had a hello@ address in the footer and no form. It
also had no LINK — the app's dialog opened from a button and nowhere else, so
there was no address to hand a tester. Now:

  - every page's footer byline (engine/shared/footer-byline.txt) links here;
  - the apps open their own dialog from `#feedback` or `#feedback=<text>`
    (engine/index.html/feedback.txt), which keeps the point and layers the
    report is about;
  - this page reads the same `#feedback=<text>`, plus `#page=<address>` for
    the page being reported. With no `page=` it takes the address the reader
    came from, when that is on this site.

THE HASH, NOT THE QUERY STRING. GoatCounter sends location.search with every
hit, so a `?feedback=` would put what a reader wrote into the analytics record.
The fragment never leaves the browser. Nothing on this page is sent anywhere
until the reader presses one of the two send buttons, which open a GitHub issue
or an e-mail draft for them to review — the same two routes the apps offer, to
the same repository and the same address.

    python3 scripts/build_feedback_page.py           # write feedback.html
    python3 scripts/build_feedback_page.py --check   # the CI drift gate
"""

import argparse
import difflib
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from build_privacy_page import (  # noqa: E402
    CONTACT, REPO_URL, SITE, esc, render_page,
)

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGE = os.path.join(REPO_ROOT, "feedback.html")
CANONICAL = SITE + "feedback.html"
METROS = os.path.join(REPO_ROOT, "metros.json")

TITLE = "Report a problem or leave a comment — districtry"
DESC = ("Tell districtry about a wrong district, a wrong name or a broken page, "
        "or leave a comment. Sent as a GitHub issue or an e-mail you review first.")
SUB = "Found something wrong, or have a suggestion? Say what and where."
GENERATOR = (
    "<!-- GENERATED by scripts/build_feedback_page.py. `--check` fails when this\n"
    "     file and the script disagree. Do NOT hand-edit. -->")
ISSUES = REPO_URL + "/issues/new"
SUBJECT = "districtry feedback"


def fail(msg):
    print("build-feedback-page: FAIL — %s" % msg, file=sys.stderr)
    sys.exit(1)


def fleet():
    """The apps, from metros.json, for the footer links and the note on
    reporting a map view. Read, never listed here."""
    with open(METROS, encoding="utf-8") as fh:
        data = json.load(fh)
    rows = data.get("metros") if isinstance(data, dict) else data
    out = []
    for m in rows or []:
        url, name = m.get("url"), m.get("landing_name") or m.get("name")
        if url and name:
            out.append({"url": url, "name": name})
    if len(out) < 2:
        fail("metros.json lists fewer than two apps — is it still the fleet list?")
    return out


def jsonld():
    return json.dumps({
        "@context": "https://schema.org",
        "@type": "ContactPage",
        "@id": CANONICAL,
        "url": CANONICAL,
        "name": TITLE,
        "description": DESC,
        "inLanguage": "en-US",
        "isPartOf": {"@id": SITE + "#website"},
        "breadcrumb": {
            "@type": "BreadcrumbList",
            "itemListElement": [
                {"@type": "ListItem", "position": 1, "name": "districtry", "item": SITE},
                {"@type": "ListItem", "position": 2, "name": "Report a problem"},
            ],
        },
    }, indent=2)


# The form's own styles, in the shell's token vocabulary.
EXTRA_CSS = """
<style>
.fb-form { max-width: 720px; }
.fb-form label { display: block; font-weight: 600; margin: 18px 0 6px; }
.fb-form .hint { color: var(--muted); font-size: 14px; margin: 4px 0 0; }
.fb-form input, .fb-form textarea {
  width: 100%; font: inherit; color: var(--ink); background: var(--surface);
  border: 1px solid var(--border); border-radius: 8px; padding: 10px 12px;
}
.fb-form textarea { min-height: 180px; resize: vertical; }
.fb-actions { display: flex; flex-wrap: wrap; gap: 10px; margin: 18px 0 8px; }
.fb-actions button, .fb-actions a {
  display: inline-flex; align-items: center; min-height: 40px;
  font: 600 14px/1 var(--font-body); border-radius: 999px; padding: 10px 18px;
  cursor: pointer; text-decoration: none;
}
.fb-primary { background: var(--brand-700); color: var(--paper); border: 1px solid var(--brand-700); }
.fb-secondary { background: transparent; color: var(--brand-700); border: 1px solid var(--border); }
.fb-primary:hover, .fb-secondary:hover { border-color: var(--brand-600); }
</style>
"""


def body(apps):
    app_links = ", ".join('<a href="%s">%s</a>' % (esc(a["url"]), esc(a["name"])) for a in apps)
    script = r"""
<script>
(function () {
  var ISSUES = %(issues)s, EMAIL = %(email)s, SUBJECT = %(subject)s;
  var text = document.getElementById("fb-text");
  var page = document.getElementById("fb-page");
  var gh = document.getElementById("fb-github");
  var mail = document.getElementById("fb-email");
  var copy = document.getElementById("fb-copy");
  function hashParam(name) {
    var parts = location.hash.replace(/^#/, "").split("&");
    for (var i = 0; i < parts.length; i++) {
      var eq = parts[i].indexOf("=");
      if ((eq < 0 ? parts[i] : parts[i].slice(0, eq)) !== name) continue;
      if (eq < 0) return "";
      try { return decodeURIComponent(parts[i].slice(eq + 1).replace(/\+/g, " ")); } catch (e) { return ""; }
    }
    return null;
  }
  // The page being reported: #page= when the link names it, otherwise the
  // page the reader came from, when that is on this site.
  var from = "";
  try {
    var ref = document.referrer ? new URL(document.referrer) : null;
    if (ref && ref.origin === location.origin && ref.pathname !== location.pathname) from = ref.href;
  } catch (e) {}
  // Read on load, and again when only the part after # changes, which a
  // browser does without reloading the page.
  function fromHash(first) {
    var named = hashParam("page"), prefill = hashParam("feedback");
    if (named || first) page.value = named || from;
    if (prefill) text.value = prefill; // .value: the text is never parsed as markup
  }
  fromHash(true);
  window.addEventListener("hashchange", function () { fromHash(false); refresh(); });
  function report() {
    var lines = [];
    var t = (text.value || "").trim();
    if (t) lines.push(t);
    lines.push("", "---");
    lines.push("Page: " + ((page.value || "").trim() || "(not given)"));
    if (navigator.userAgent) lines.push("Browser: " + navigator.userAgent);
    return lines.join("\n");
  }
  function refresh() {
    mail.href = "mailto:" + EMAIL + "?subject=" + encodeURIComponent(SUBJECT) +
      "&body=" + encodeURIComponent(report());
  }
  text.addEventListener("input", refresh);
  page.addEventListener("input", refresh);
  mail.addEventListener("click", refresh);
  gh.addEventListener("click", function () {
    window.open(ISSUES + "?title=" + encodeURIComponent("Bug report / comment") +
      "&body=" + encodeURIComponent(report()), "_blank", "noopener");
  });
  copy.addEventListener("click", function () {
    var parts = [];
    var p = (page.value || "").trim(), t = (text.value || "").trim();
    if (p) parts.push("page=" + encodeURIComponent(p));
    if (t) parts.push("feedback=" + encodeURIComponent(t));
    var url = location.origin + location.pathname + (parts.length ? "#" + parts.join("&") : "");
    var done = function (ok) {
      copy.textContent = ok ? "Copied!" : "Copy failed";
      setTimeout(function () { copy.textContent = "Copy a link to this form"; }, 1600);
    };
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(url).then(function () { done(true); }, function () { done(false); });
    } else { done(false); }
  });
  refresh();
})();
</script>""" % {"issues": json.dumps(ISSUES), "email": json.dumps(CONTACT),
                 "subject": json.dumps(SUBJECT)}
    return """
  <section>
    <p>Describe what is wrong or what you would like, then file it as a GitHub issue or send it
      by e-mail. Either one opens a draft for you to read and edit first; nothing is sent until
      you send it. Every report gets a reply.</p>
    <p class="cta-note">Reporting something on a map? Use the form inside the app instead
      (&ldquo;Report a bug or leave a comment&rdquo; at the foot of its panel): it attaches the
      point and layers you were looking at. The apps: %(apps)s.</p>
    <form class="fb-form" onsubmit="return false">
      <label for="fb-page">Which page is this about?</label>
      <input id="fb-page" type="url" inputmode="url" autocomplete="off"
        placeholder="https://districtry.com/…" />
      <p class="hint">Filled in with the page you came from. Change it if the problem is somewhere else.</p>
      <label for="fb-text">Your report or comment</label>
      <textarea id="fb-text" placeholder="What is wrong, what you expected, and where&hellip;"></textarea>
      <div class="fb-actions">
        <button type="button" class="fb-primary" id="fb-github">Open a GitHub issue</button>
        <a class="fb-secondary" id="fb-email" href="mailto:%(email)s">Send by e-mail instead</a>
        <button type="button" class="fb-secondary" id="fb-copy">Copy a link to this form</button>
      </div>
      <p class="hint">A GitHub issue is public. The e-mail goes to %(email)s. Either one carries
        what you wrote, the page address and your browser's user-agent string.</p>
    </form>
  </section>
%(script)s
""" % {"apps": app_links, "email": esc(CONTACT), "script": script}


def build():
    apps = fleet()
    links = '<a href="/about.html">About</a>\n      <a href="/privacy.html">Privacy</a>'
    return render_page(
        pagetitle="Report a problem", pagesub=SUB, generator=GENERATOR,
        body=body(apps).replace("%", "%%"),
        title=TITLE, desc=DESC, jsonld=jsonld(),
        footerlinks=links, canonical=CANONICAL,
    ).replace("</head>", EXTRA_CSS.strip() + "\n</head>", 1)


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="fail on drift rather than writing")
    args = ap.parse_args()
    page = build()
    if page.lower().count("</script") != page.lower().count("<script"):
        fail("the page's script tags do not balance — a literal closing tag in a "
             "comment or string ends the element early")
    current = open(PAGE, encoding="utf-8").read() if os.path.exists(PAGE) else None
    if args.check:
        if current is None:
            fail("feedback.html does not exist. Run `python3 scripts/build_feedback_page.py`.")
        if current != page:
            for line in list(difflib.unified_diff(
                    current.split("\n"), page.split("\n"), "shipped", "built",
                    lineterm="", n=1))[:12]:
                print("  " + line)
            fail("feedback.html has drifted from its generator. Regenerate rather "
                 "than editing the page.")
        print("build-feedback-page: OK — current")
        return
    if current == page:
        print("build-feedback-page: OK — no change")
        return
    with open(PAGE, "w", encoding="utf-8") as f:
        f.write(page)
    print("build-feedback-page: wrote feedback.html")


if __name__ == "__main__":
    main()
