#!/usr/bin/env python3
"""
/ai.html — how districtry uses AI: what the coding agents do in building it,
what no AI does, what the person who runs it does, and how the work is checked.
GENERATED on the same shell as /about.html, /privacy.html and /feedback.html.

WHY IT EXISTS (2026-09-23). Most of this repository is written by AI coding
agents, and nothing on the site said so or said where AI stops. A reader
deciding whether to trust a name on a card could not find out that no model
produces the names, or that the person who runs the project does not read
every change. Both are true, and a reader should be told both.

A DRAFT OF THIS PAGE CLAIMED A PERSON APPROVES EVERY CHANGE, AND THAT WAS
FALSE. Since 2026-09-19 a coordinating agent session has held standing
authority from the operator to review and merge the other agents' pull
requests and the weekly roster refreshes; before that, #1024 records a weekly
refresh that put 112 strings that were not names on Rock Island County's
municipal cards for fifteen days. Five commits touching app or roster files
went straight to main without a pull request (two on 2026-09-03, three on
2026-08-24/25), and the deploy smoke-tests the Illinois app alone. So the page
claims none of: a person reviews every change, every change is a pull
request, every app is browser-tested before a deploy. It says what is true.

WHY IT IS GENERATED WHEN IT CARRIES NO NUMBER. The prose is fixed, but the
shell is not: tokens, fonts, favicon, footer byline and the counter move with
the other root pages, and a hand-written copy of that shell is how a page falls
out of step with them. The generator exists for the shell and for the checks
below; the prose is written here, once.

NO NUMBERS, DELIBERATELY. The page states no count, share or date. Every
number about this project moves weekly, and a page about how the project is
run should not carry a figure that is wrong a fortnight later. It links the
commit history instead.

WHAT IT CHECKS, because each is a claim the page makes:

  1. No served file calls an AI service. Every .html and .js file outside the
     build-only folders is searched for the API hosts of the known AI
     services. This is a DENYLIST: it cannot prove that an unknown host is not
     one. The complete list of what a browser contacts is the privacy page's
     recipients table, which build_privacy_page.py measures.
  2. No workflow, and no script a workflow can run, uses an AI service: the
     same hosts, plus AI actions, SDK imports, the Claude CLI's print mode and
     AI API-key names. This backs "the weekly updates are read by ordinary
     code". This file is the one script excluded, because it names them.
  3. A workflow that pushes opens a pull request. Every workflow running
     `git push` must also run `gh pr create`, unless DIRECT_PUSH records why
     not. Each entry there FAILS when its file is gone, no longer pushes, or
     has started opening a pull request, so the list cannot rot. /about.html
     makes the same claim ("opens a pull request rather than committing").
  4. robots.txt still says what the page says about AI systems reading the
     site: the Content-Signal for `*`, read by robots_policy.py.

WHAT IT CANNOT CHECK. Who reviews and merges a pull request is not recorded in
the tree, and neither is the traffic report being refreshed by a scheduled
agent. The page states both as the project's practice; a change to that
practice is a change to the prose here.

    python3 scripts/build_ai_page.py           # write ai.html
    python3 scripts/build_ai_page.py --check   # drift gate + the four checks
"""

import argparse
import difflib
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from build_privacy_page import (  # noqa: E402
    REPO_URL, SITE, render_page,
)
import robots_policy  # noqa: E402

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGE = os.path.join(REPO_ROOT, "ai.html")
CANONICAL = SITE + "ai.html"
WORKFLOW_DIR = os.path.join(REPO_ROOT, ".github", "workflows")
SELF = os.path.abspath(__file__)

TITLE = "How districtry uses AI"
DESC = ("What AI coding agents do in building districtry, what no AI does, what "
        "the person who runs it does, and how the work is checked.")
SUB = "What the AI agents do, what no AI does, and how the work is checked."
GENERATOR = (
    "<!-- GENERATED by scripts/build_ai_page.py. `--check` fails when this file\n"
    "     and the script disagree, and when a claim on it stops holding. Do NOT\n"
    "     hand-edit. -->")


def fail(msg):
    print("build-ai-page: FAIL — %s" % msg, file=sys.stderr)
    sys.exit(1)


# ---- the checks ----------------------------------------------------------

# The API hosts of the AI services a page or a job could call. Matched as
# lowercase substrings, so a regional or per-resource name (a Bedrock region,
# an Azure OpenAI resource) is caught by its suffix.
AI_HOSTS = (
    "api.anthropic.com",
    "api.openai.com",
    "chatgpt.com",
    "openai.azure.com",
    "generativelanguage.googleapis.com",
    "aiplatform.googleapis.com",
    "bedrock-runtime.",
    "api.mistral.ai",
    "api.cohere.com",
    "api.cohere.ai",
    "api-inference.huggingface.co",
    "router.huggingface.co",
    "api.groq.com",
    "api.together.xyz",
    "openrouter.ai",
    "api.perplexity.ai",
    "api.x.ai",
    "api.deepseek.com",
    "api.fireworks.ai",
    "api.replicate.com",
)

# What an automated job would carry to use one, beyond the hosts.
AUTOMATION_MARKERS = (
    "anthropics/claude-code-action",
    "anthropics/claude-code-base-action",
    "@anthropic-ai/",
    "anthropic_api_key",
    "openai_api_key",
    "gemini_api_key",
    "mistral_api_key",
    "cohere_api_key",
)
SDK_IMPORT = re.compile(
    r"^\s*(?:import|from)\s+(anthropic|openai|google\.generativeai|google\.genai|"
    r"mistralai|cohere|groq)\b", re.M)
CLAUDE_CLI = re.compile(r"\bclaude\s+(?:-p|--print)\b")

# Folders the deploy never publishes. Searching them for check 1 would only
# add noise; the automation folders are check 2's subject.
BUILD_ONLY = {".git", ".github", ".claude", "node_modules", "scripts", "docs",
              "engine"}

# Workflows that push to main without a pull request, and why that is not an
# officeholder or a boundary. Re-audited every run.
DIRECT_PUSH = {
    "update-search-performance.yml":
        "Google Search Console counts for this site's own pages, for the "
        "traffic report; no officeholder, boundary or app file (2026-09-14)",
    "update-bing-performance.yml":
        "Bing Webmaster counts for this site's own pages, for the traffic "
        "report; no officeholder, boundary or app file (2026-09-14)",
    "update-traffic-data.yml":
        "GoatCounter visit counts for this site, for the traffic report; no "
        "officeholder, boundary or app file (2026-09-14)",
}

# What the page says about AI systems reading the site, as robots.txt's
# Content-Signal for `*` must still say it.
EXPECTED_SIGNAL = {"search": "yes", "ai-input": "yes", "ai-train": "no",
                   "use": "reference"}


def rel(path):
    return os.path.relpath(path, REPO_ROOT)


def read(path):
    with open(path, encoding="utf-8", errors="replace") as fh:
        return fh.read()


def served_files():
    out = []
    for root, dirs, files in os.walk(REPO_ROOT):
        dirs[:] = sorted(d for d in dirs if d not in BUILD_ONLY)
        for name in sorted(files):
            if name.endswith((".html", ".js")):
                out.append(os.path.join(root, name))
    return out


def automation_files():
    out = sorted(os.path.join(WORKFLOW_DIR, n) for n in os.listdir(WORKFLOW_DIR)
                 if n.endswith((".yml", ".yaml")))
    for root, dirs, files in os.walk(REPO_ROOT):
        # Vendored libraries are gitignored copies fetched for the sandbox, so
        # they exist here and not in CI; neither is a job's own code.
        dirs[:] = sorted(d for d in dirs
                         if d not in (".git", "node_modules", "vendor"))
        if "scripts" not in rel(root).split(os.sep):
            continue
        for name in sorted(files):
            path = os.path.join(root, name)
            if name.endswith((".py", ".mjs", ".js", ".sh")) and os.path.abspath(path) != SELF:
                out.append(path)
    return out


def check_served():
    files = served_files()
    if not any(rel(p).endswith("/index.html") for p in files):
        fail("found no instance index.html to search — has the tree moved?")
    hits = []
    for path in files:
        text = read(path).lower()
        hits += ["%s names %s" % (rel(path), h) for h in AI_HOSTS if h in text]
    if hits:
        fail("the page says no app sends anything to an AI service, and a served "
             "file names one:\n  " + "\n  ".join(hits) + "\nEither remove the "
             "call or rewrite the page, and name the new recipient on the privacy "
             "page.")
    return len(files)


def check_automation():
    files = automation_files()
    hits = []
    for path in files:
        raw = read(path)
        text = raw.lower()
        hits += ["%s names %s" % (rel(path), m)
                 for m in AI_HOSTS + AUTOMATION_MARKERS if m in text]
        m = SDK_IMPORT.search(raw)
        if m:
            hits.append("%s imports %s" % (rel(path), m.group(1)))
        if CLAUDE_CLI.search(raw):
            hits.append("%s runs the Claude CLI in print mode" % rel(path))
    if hits:
        fail("the page says the weekly updates are read by ordinary code, and "
             "automation uses an AI service:\n  " + "\n  ".join(hits))
    return len(files)


def check_pushes():
    pushes = re.compile(r"\bgit\s+push\b")
    opens_pr = re.compile(r"\bgh\s+pr\s+create\b")
    names = sorted(n for n in os.listdir(WORKFLOW_DIR) if n.endswith((".yml", ".yaml")))
    problems, pr_count = [], 0
    for name in names:
        text = read(os.path.join(WORKFLOW_DIR, name))
        if not pushes.search(text):
            continue
        if opens_pr.search(text):
            pr_count += 1
            if name in DIRECT_PUSH:
                problems.append("%s is in DIRECT_PUSH and now opens a pull "
                                "request — remove the entry" % name)
        elif name not in DIRECT_PUSH:
            problems.append("%s pushes without opening a pull request, and "
                            "DIRECT_PUSH does not say why" % name)
    for name in sorted(DIRECT_PUSH):
        path = os.path.join(WORKFLOW_DIR, name)
        if not os.path.exists(path):
            problems.append("DIRECT_PUSH names %s, which no longer exists" % name)
        elif not pushes.search(read(path)):
            problems.append("DIRECT_PUSH names %s, which no longer pushes" % name)
    if problems:
        fail("a workflow that changes the site either opens a pull request or "
             "is recorded:\n  " + "\n  ".join(problems))
    if pr_count < 2:
        fail("found %d workflow(s) opening a pull request — is this still the "
             "workflow folder?" % pr_count)
    return pr_count


def check_signal():
    policy = robots_policy.RobotsPolicy(read(os.path.join(REPO_ROOT, "robots.txt")))
    signal = policy.content_signal("*") or {}
    wrong = ["%s=%s (robots.txt says %s)" % (k, v, signal.get(k, "nothing"))
             for k, v in sorted(EXPECTED_SIGNAL.items()) if signal.get(k) != v]
    if wrong:
        fail("the page's last section restates robots.txt's Content-Signal, and "
             "they now disagree on " + ", ".join(wrong) + ". Rewrite that "
             "section and EXPECTED_SIGNAL together.")


# ---- the page ------------------------------------------------------------

def jsonld():
    return json.dumps({
        "@context": "https://schema.org",
        "@type": "WebPage",
        "@id": CANONICAL,
        "url": CANONICAL,
        "name": TITLE,
        "description": DESC,
        "inLanguage": "en-US",
        "isPartOf": {"@id": SITE + "#website"},
        "author": {"@id": SITE + "#author"},
        "breadcrumb": {
            "@type": "BreadcrumbList",
            "itemListElement": [
                {"@type": "ListItem", "position": 1, "name": "districtry", "item": SITE},
                {"@type": "ListItem", "position": 2, "name": "How districtry uses AI"},
            ],
        },
    }, indent=2)


def body():
    return """
  <section>
    <p class="lede">Most of districtry's code and much of its writing are produced by AI coding
      agents, directed by the one person who runs the project. <strong>The app you use has no AI
      in it.</strong> This page says what the agents do, what they do not do, what the person
      does, and how the work is checked.</p>
  </section>

  <section>
    <h2>What an AI agent does</h2>
    <ul class="facts">
      <li><strong>Writes code:</strong> the apps, the scripts that read each government's
        published data, and the automated checks every change has to pass.</li>
      <li><strong>Researches sources:</strong> where a county publishes its board districts, what
        its certified election results say, and how its districts can be built from what it
        publishes.</li>
      <li><strong>Drafts text:</strong> the explanatory pages, the records of what data is
        missing, the history pages, and e-mails asking county offices for what nobody
        publishes.</li>
      <li><strong>Reviews and merges changes.</strong> Several agents work at once, most of them
        on one state each, and one more coordinates them. The coordinating agent reviews the
        other agents' pull requests and the weekly roster updates, and merges them under
        standing authority from the person who runs the project. Its standing rule is to test
        each change on the combined code before merging it, and to hold any change it cannot
        verify.</li>
      <li><strong>Refreshes the traffic report.</strong> A scheduled agent rebuilds the site's
        <a href="/traffic.html">traffic page</a> from its analytics each day and commits it
        directly, without a pull request.</li>
    </ul>
    <p>The agents are Claude Code, from Anthropic, working in the project's public
      repository.</p>
  </section>

  <section>
    <h2>What a person does</h2>
    <ul class="facts">
      <li><strong>Sets the rules the work follows:</strong> never guess an officeholder, cite
        every source, and write down every absence.</li>
      <li><strong>Makes the calls the sources cannot settle.</strong> For example, a district map
        whose populations are far from equal ships only after the county confirms in writing
        that it is the current map.</li>
      <li><strong>Sends every e-mail.</strong> An agent may draft a message to a county clerk; a
        person reads it, edits it and sends it. Nothing is sent automatically.</li>
      <li><strong>Does not read every change.</strong> The person reads what the coordinating
        agent reports and answers the questions the agents raise. For everything else, the
        project relies on the rules and on the checks below.</li>
    </ul>
  </section>

  <section>
    <h2>What no AI does</h2>
    <p><strong>No AI runs in the app.</strong> Each app is a set of static files that reads public
      data sources. Nothing you click, type or paste, including a list in the Bulk Address
      Checker, is sent to an AI service. The <a href="/privacy.html">privacy page</a> lists
      everything your browser contacts.</p>
    <p><strong>No answer is made up by a model.</strong> Every name, district and boundary in the
      apps is taken from a published source, and each app's sources page names it. Most are read
      by scripts, which an AI agent may have written. A few rosters are copied in from a page or
      document no script can read, such as a list a county clerk sent by e-mail. Where an agent
      worked out how a county's districts are built, from a map or from election results, the
      script that builds them checks the result against independent figures, such as census
      population or the number of precincts that voted in each district, and refuses to build
      if they disagree.</p>
    <p><strong>The weekly updates are read by ordinary code, not by AI.</strong> Scheduled jobs
      re-read each source and, when an officeholder changes, propose the change as a pull
      request, which is checked, reviewed and merged like any other change.</p>
  </section>

  <section>
    <h2>How it is checked</h2>
    <p>AI agents produce confident wrong answers, and so do people. The project assumes both.
      Every pull request runs automated checks that confirm each app still loads and answers
      known points correctly, that no roster has stopped publishing a detail it used to carry,
      that links between the site's own pages resolve, and that figures written into the
      documentation still match the data.</p>
    <p>Mistakes have still reached the site, including officeholder names that a script misread
      from a county's page. When one is found it is corrected, and where a check could have
      caught it, one is added. Some of those cases are described on the history pages, and every
      change, including each fix, is in the public commit history.</p>
  </section>

  <section>
    <h2>If something is wrong</h2>
    <p>Say so and it gets fixed:
      <a href="mailto:corrections@overberg.co?subject=districtry%%20correction">corrections@overberg.co</a>,
      the <a href="/feedback.html">report form</a> linked at the foot of each page, or
      <a href="%(repo)s/issues/new" target="_blank" rel="noopener">an issue on GitHub</a>.
      The code and its full history are
      <a href="%(repo)s" target="_blank" rel="noopener">public</a>,
      and commits made with an AI agent usually name it as a co-author.</p>
  </section>

  <section>
    <h2>AI systems reading this site</h2>
    <p>Search engines and AI tools are welcome to use these pages to answer questions, by
      reference and with a link back to the page that names the person. Training on them is
      reserved. <a href="/robots.txt">robots.txt</a> says so in its Content-Signal line,
      <a href="/llms.txt">/llms.txt</a> is a short guide for a client reading the site, and the
      <a href="/about.html">About page</a> has more.</p>
  </section>
""" % {"repo": REPO_URL}


EXTRA_CSS = """
<style>
.facts { margin: 0; padding-left: 1.15rem; display: grid; gap: 0.5rem; }
.facts li { max-width: 68ch; }
/* A paragraph after a list, which /about.html never has: the list carries no
   bottom margin, so give the paragraph the gap the shell puts under one. */
.facts + p { margin-top: 14px; }
</style>
"""


def build():
    links = '<a href="/about.html">About</a>\n      <a href="/privacy.html">Privacy</a>'
    # render_page runs the page through one more % substitution for the shell's
    # own slots; the body's literal %20 in the mailto is escaped here, after
    # the body's own substitution, the way build_about_page.py does it.
    return render_page(
        pagetitle="How it uses AI", pagesub=SUB, generator=GENERATOR,
        body=body().replace("%", "%%"),
        title=TITLE, desc=DESC, jsonld=jsonld(),
        footerlinks=links, canonical=CANONICAL,
    ).replace("</head>", EXTRA_CSS.strip() + "\n</head>", 1)


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="fail on drift or on a claim that no longer holds, rather "
                         "than writing")
    args = ap.parse_args()

    served = check_served()
    automation = check_automation()
    prs = check_pushes()
    check_signal()
    claims = ("%d served files name no AI service; %d workflow and script files use "
              "none; %d pushing workflows open a pull request and %d push directly, "
              "each recorded; robots.txt's Content-Signal matches"
              % (served, automation, prs, len(DIRECT_PUSH)))

    page = build()
    if page.lower().count("</script") != page.lower().count("<script"):
        fail("the page's script tags do not balance — a literal closing tag in a "
             "comment or string ends the element early")
    current = read(PAGE) if os.path.exists(PAGE) else None
    if args.check:
        if current is None:
            fail("ai.html does not exist. Run `python3 scripts/build_ai_page.py`.")
        if current != page:
            for line in list(difflib.unified_diff(
                    current.split("\n"), page.split("\n"), "shipped", "built",
                    lineterm="", n=1))[:12]:
                print("  " + line)
            fail("ai.html has drifted from its generator. Regenerate rather than "
                 "editing the page.")
        print("build-ai-page: OK — current; " + claims)
        return
    if current == page:
        print("build-ai-page: OK — no change; " + claims)
        return
    with open(PAGE, "w", encoding="utf-8") as fh:
        fh.write(page)
    print("build-ai-page: wrote ai.html; " + claims)


if __name__ == "__main__":
    main()
