#!/usr/bin/env python3
"""Build fleet-outlines.json: where each live instance answers, for the hand-off.

WHY THIS FILE EXISTS. Every app sends a reader to a sibling instance when they
select a place the sibling serves (ENGINE metro-portal). Until 2026-09-27 that
decision was made with RECTANGLES, twice over: the app first asked whether the
point was inside its OWN bounding box, and if not, which sibling's box held it,
settling overlaps by the nearest box centre. Simulated over 35 real places in
all six apps, 79 selections went to the wrong place, in three ways:

  * an app's own box swallows its neighbours. Illinois's box reaches -91.55, so
    a click on Davenport, Dubuque, Burlington or Keokuk from Illinois did
    nothing; Michigan's box, which is water-inclusive and runs west to -90.42,
    held Chicago, Milwaukee, Green Bay and Madison, so none of those handed off
    from Michigan at all;
  * sibling boxes overlap and the nearest-centre tie-break picks the wrong one:
    from four of the apps, Marquette and Iron Mountain went to Wisconsin and
    Davenport to Illinois;
  * a box claims states nobody serves: Gary and St. Louis were sent to the
    Illinois app and Hartford and Newark to New York, where nothing answers.

A state outline answers all three. Each app already carries its own, at full
detail, for the coverage wash; this file is every live instance's outline
SIMPLIFIED to about 200 m and put in one place, so an app can ask about its
siblings without downloading five full outlines (together about 650 KB). The
whole file is about 18 KB gzipped, and an app fetches it only when a selection
falls outside its own outline.

WHICH OUTLINE is the ground where an instance answers ANYTHING, which is its
widest band: the state outline for Illinois, New York and Wisconsin (their
statewide layers answer across it), the statewide coverage ring for Iowa and
Michigan, and the city for San Francisco. `SOURCES` is keyed by the instance's
tag and FAILS when metros.json names an instance it does not know, so a new
state cannot go live with no outline to be handed off to.

`--check` is stdlib-only and offline, the tiger-mirror pattern: shapely's
output is not guaranteed byte-identical across versions, so the check does not
rebuild. It asserts the file names exactly the ids in metros.json, that each
id's recorded source path and SHA-256 still match the file in the tree (a
changed outline without a rebuild fails), and that every geometry is a Polygon
or MultiPolygon with closed rings.

Usage:
    python3 scripts/build_fleet_outlines.py          # rebuild (needs shapely)
    python3 scripts/build_fleet_outlines.py --check  # CI drift gate
"""
import argparse
import hashlib
import json
import os
import sys

REPO = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
OUT = os.path.join(REPO, "fleet-outlines.json")
METROS = os.path.join(REPO, "metros.json")

# tag -> the outline of the widest ground that instance answers on.
SOURCES = {
    "il": "il/data/app/il-state-outline.json",
    "ny": "ny/data/app/ny-state-outline.json",
    "ca": "ca/data/app/san-francisco-county-outline.json",
    "wi": "wi/data/app/wi-state-outline.json",
    "ia": "ia/data/app/metro-outline.json",
    "mi": "mi/data/app/metro-outline.json",
}

# Degrees. 0.002 is about 220 m north-south and 165 m east-west at 42 N.
# Measured 2026-09-27: 0.002 gives 18 KB gzipped, 0.005 gives 9 KB and 0.01
# gives 6 KB. The coarser settings would save a few kilobytes on a file fetched
# only when a selection leaves an app's own outline, and cost accuracy on the
# river borders where most hand-offs happen, so the finer one ships.
TOLERANCE = 0.002
DECIMALS = 4  # about 11 m, well inside the tolerance


def fail(msg):
    print("build_fleet_outlines: FAIL: " + msg, file=sys.stderr)
    sys.exit(1)


def sha256(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def load_metros():
    with open(METROS, encoding="utf-8") as f:
        metros = json.load(f)["metros"]
    for m in metros:
        if m["tag"] not in SOURCES:
            fail("metros.json names instance %r (%s) and SOURCES has no outline for it "
                 "— add the file its widest band is drawn from" % (m["tag"], m["id"]))
    return metros


def round_coords(obj):
    if isinstance(obj, float):
        return round(obj, DECIMALS)
    if isinstance(obj, list):
        return [round_coords(x) for x in obj]
    if isinstance(obj, dict):
        return {k: round_coords(v) for k, v in obj.items()}
    return obj


def build():
    from shapely.geometry import mapping, shape
    from shapely.ops import unary_union

    metros = load_metros()
    out = {
        "$comment": "GENERATED by scripts/build_fleet_outlines.py — do not hand-edit. "
                    "Each live instance's widest outline, simplified to about 200 m, "
                    "read by ENGINE metro-portal to decide which app a selected point "
                    "belongs to. Keys are metros.json ids.",
        "tolerance_deg": TOLERANCE,
        "sources": {},
        "outlines": {},
    }
    for m in metros:
        rel = SOURCES[m["tag"]]
        path = os.path.join(REPO, rel)
        if not os.path.isfile(path):
            fail("%s (instance %s) does not exist" % (rel, m["tag"]))
        with open(path, encoding="utf-8") as f:
            d = json.load(f)
        feats = d["features"] if d.get("type") == "FeatureCollection" else [d]
        geoms = [shape(f["geometry"] if f.get("type") == "Feature" else f) for f in feats]
        g = unary_union(geoms).simplify(TOLERANCE, preserve_topology=True)
        if g.is_empty:
            fail("%s simplified to nothing" % rel)
        out["sources"][m["id"]] = {"path": rel, "sha256": sha256(path)}
        out["outlines"][m["id"]] = round_coords(json.loads(json.dumps(mapping(g))))
    txt = json.dumps(out, separators=(",", ":"), sort_keys=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(txt + "\n")
    print("build_fleet_outlines: wrote %s (%d bytes, %d instances)"
          % (os.path.relpath(OUT, REPO), len(txt) + 1, len(out["outlines"])))


def closed_rings(geom):
    polys = [geom["coordinates"]] if geom["type"] == "Polygon" else geom["coordinates"]
    for poly in polys:
        for ring in poly:
            if len(ring) < 4 or ring[0] != ring[-1]:
                return False
    return True


def check():
    metros = load_metros()
    try:
        with open(OUT, encoding="utf-8") as f:
            data = json.load(f)
    except OSError:
        fail("fleet-outlines.json is missing — run scripts/build_fleet_outlines.py")
    ids = sorted(m["id"] for m in metros)
    if sorted(data.get("outlines", {})) != ids or sorted(data.get("sources", {})) != ids:
        fail("fleet-outlines.json names %s, metros.json names %s — rebuild"
             % (sorted(data.get("outlines", {})), ids))
    for m in metros:
        src = data["sources"][m["id"]]
        want = SOURCES[m["tag"]]
        if src["path"] != want:
            fail("%s was built from %s, SOURCES now says %s — rebuild" % (m["id"], src["path"], want))
        path = os.path.join(REPO, want)
        if not os.path.isfile(path):
            fail("%s (instance %s) does not exist" % (want, m["tag"]))
        if sha256(path) != src["sha256"]:
            fail("%s changed since fleet-outlines.json was built — rebuild it so the "
                 "hand-off follows the new outline" % want)
        geom = data["outlines"][m["id"]]
        if geom.get("type") not in ("Polygon", "MultiPolygon") or not closed_rings(geom):
            fail("%s's outline is not a Polygon/MultiPolygon of closed rings" % m["id"])
    print("build_fleet_outlines: OK — %d instances, every outline matches its source" % len(ids))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="offline drift gate (stdlib only)")
    args = ap.parse_args()
    check() if args.check else build()


if __name__ == "__main__":
    main()
