#!/usr/bin/env python3
"""
/about.html — what this site is, where its answers come from, and how to
correct one. GENERATED, and every number on it is read from the file that
owns it.

WHY IT EXISTS. Measured 2026-09-15, /about.html, /methodology and /corrections
all returned 404, on a domain whose answers compete in search results with the
county and state pages they are drawn from. A reader deciding whether to trust
a name on a map had nowhere on this site to find out who publishes it, how
often it is re-read, or what happens when it is wrong. The footers pointed at
overberg.co/why/, which is a different site about a different thing.

WHY IT IS GENERATED RATHER THAN WRITTEN. An about page is where a project
states its size, and a stated size is the thing that goes stale first. "Six
apps", "91 counties", "2,711 officeholders" — every one of those has moved
inside a fortnight in this repo's history. So the page carries no number this
script did not read from a shipped file on the run that wrote it, and `--check`
fails the build when the tree moves under it.

WHAT IT DELIBERATELY DOES NOT DO. It does not restate the privacy page, which
MEASURES each app and is the only place claims about transmission belong; it
links it. It does not list counties, which the per-state hubs already index.
And it names no date it did not read: each instance's verified date comes from
that instance's own worksheet.

    python3 scripts/build_about_page.py           # write about.html
    python3 scripts/build_about_page.py --check   # the CI drift gate
"""

import argparse
import difflib
import glob
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from build_privacy_page import (  # noqa: E402
    REPO_URL, SITE, esc, render_page,
)
import robots_policy  # noqa: E402

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def fail(msg):
    """This module's own. Importing build_privacy_page's prints
    `build-privacy-page: FAIL` and sends whoever reads it to the wrong file."""
    print("build-about-page: FAIL — %s" % msg, file=sys.stderr)
    sys.exit(1)
PAGE = os.path.join(REPO_ROOT, "about.html")
CANONICAL = SITE + "about.html"

TITLE = "About districtry"
DESC = ("Who builds districtry, where every boundary and every officeholder "
        "name comes from, how often each is re-read, and how to send a "
        "correction.")
SUB = "Who makes it, where the answers come from, and how to correct one."

GENERATOR = (
    "<!-- GENERATED by scripts/build_about_page.py. Every number here is read\n"
    "     from a shipped file on the run that wrote it; `--check` fails when the\n"
    "     tree moves under it. Do NOT hand-edit. -->")


def read_json(rel):
    with open(os.path.join(REPO_ROOT, rel), encoding="utf-8") as f:
        return json.load(f)


def instances():
    """Each live instance, from metros.json plus its own worksheet.

    metros.json owns the fleet list and the reader-facing name; the worksheet
    owns the layer count and the verified date. Neither is restated here.
    """
    fleet = read_json("metros.json")
    entries = fleet["metros"] if isinstance(fleet, dict) else fleet
    out = []
    for m in entries:
        tag = m.get("tag")
        if not tag:
            continue
        ws_rel = "metro-worksheet.json" if tag == "il" else "%s/metro-worksheet.json" % tag
        ws = read_json(ws_rel)
        out.append(dict(tag=tag, name=m.get("landing_name") or tag,
                        scope=m.get("scope") or "", url=m.get("url") or ("/%s/" % tag),
                        layers=len(ws.get("layers") or []),
                        verified=ws.get("verified_date") or ""))
    if len(out) < 2:
        fail("metros.json yielded %d instance(s) — the fleet list did not read"
             % len(out))
    check_illinois_scope(out)
    return out


def check_illinois_scope(fleet):
    """The one `scope` string in metros.json that tracks a list in this repo.

    Illinois's ring is a SUBSET of its state and grows county by county, so
    "93 counties" is a number that moves — and metros.json is hand-kept, which
    is exactly the kind of figure this page must not restate unchecked. The
    other four statewide instances say "all N counties", where N is the state's
    own county count and does not move; New York City and San Francisco name no
    count at all. So this checks the one that can go stale.
    """
    il = next((i for i in fleet if i["tag"] == "il"), None)
    if not il:
        return
    match = re.match(r"^(\d+) counties$", il["scope"].strip())
    if not match:
        fail("metros.json's Illinois scope is %r and this expects "
             "\"<N> counties\" — either the wording changed or the check has to"
             % il["scope"])
    from build_metro_outline import METRO_COUNTY_FIPS  # noqa: E402
    served = len(METRO_COUNTY_FIPS)
    if int(match.group(1)) != served:
        fail("metros.json says Illinois is %s and build_metro_outline's "
             "METRO_COUNTY_FIPS carries %d. The county list is the authority; "
             "fix metros.json." % (il["scope"], served))


def county_pages():
    """The per-county pages and the seats on them, from the generator that
    writes them rather than from a count typed here."""
    from build_county_pages import INSTANCES, load_instance  # noqa: E402
    pages = seats = 0
    for inst in INSTANCES:
        counties = load_instance(inst)[0]
        for rec in counties.values():
            pages += 1
            if rec["at_large"]:
                seats += len(rec["members"])
            else:
                seats += sum(len(d["members"]) for d in rec["districts"])
                seats += sum(len(ms) for _a, _h, ms in rec.get("extras") or [])
    return pages, seats


def table_names():
    """Everyone named in a generated officeholder table, and how many tables.

    COUNTED THROUGH THE GENERATOR'S OWN ROW READER, not by walking the roster
    files here. Four of those rosters are nested — a list of judges under a
    circuit, three lists of officials under a township — and reading them flat
    both MISSED every one of those people and counted each township's own name
    as a person. That is what this file said until 2026-09-16: 1,277 against a
    true 1,765, wrong in both directions at once. section_rows is the same
    function the renderer and the read-it-back verifier use, so all three
    answer with one reading.
    """
    from build_officeholder_tables import TABLES, section_rows  # noqa: E402
    total, tables = 0, 0
    for entry in TABLES:
        for section in entry["sections"]:
            field = section.get("name_field", "name")
            total += sum(1 for _seat, rec in section_rows(entry["tag"], section)
                         if (rec.get(field) or "").strip())
            tables += 1
    return total, tables


def recorded_gaps():
    n = 0
    for path in sorted(glob.glob(os.path.join(REPO_ROOT, "*", "data", "app",
                                              "coverage-gaps.json"))):
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        # One object per gap, KEYED BY ITS SLUG — not a list under a "gaps" key.
        # The first draft looked for that key, found none, and reported 0 for a
        # tree carrying 130, which is the shape of error this page exists to
        # avoid: a derived number that is quietly derived from nothing.
        if not isinstance(data, dict) or not data:
            fail("%s is not a non-empty object of gap records" % path)
        n += len(data)
    if not n:
        fail("no coverage-gaps.json in the tree carried a record")
    return n


def weekly_jobs():
    """Scheduled workflows, counted from the directory GitHub actually reads."""
    d = os.path.join(REPO_ROOT, ".github", "workflows")
    n = 0
    for name in sorted(os.listdir(d)):
        if not name.endswith((".yml", ".yaml")):
            continue
        with open(os.path.join(d, name), encoding="utf-8") as f:
            if "schedule:" in f.read():
                n += 1
    return n


def content_signal():
    with open(os.path.join(REPO_ROOT, "robots.txt"), encoding="utf-8") as f:
        policy = robots_policy.RobotsPolicy(f.read())
    return policy.content_signal("*") or {}


def jsonld(fleet):
    return json.dumps({
        "@context": "https://schema.org",
        "@type": "AboutPage",
        "@id": CANONICAL,
        "url": CANONICAL,
        "name": TITLE,
        "description": DESC,
        "inLanguage": "en-US",
        "author": {"@type": "Person", "@id": SITE + "#author",
                   "name": "Adam Overberg", "url": "https://overberg.co",
                   "email": "hello@overberg.co"},
        "isPartOf": {"@id": SITE + "#website"},
        "mainEntity": {
            "@type": "Organization",
            "@id": SITE + "#organization",
            "name": "districtry",
            "url": SITE,
            "description": DESC,
            "founder": {"@id": SITE + "#author"},
            "email": "hello@overberg.co",
            "sameAs": [REPO_URL],
            "areaServed": [{"@type": "AdministrativeArea", "name": i["name"]}
                           for i in fleet],
        },
        "breadcrumb": {
            "@type": "BreadcrumbList",
            "itemListElement": [
                {"@type": "ListItem", "position": 1, "name": "districtry", "item": SITE},
                {"@type": "ListItem", "position": 2, "name": "About"},
            ],
        },
    }, indent=2)


def fleet_rows(fleet):
    rows = []
    for i in fleet:
        rows.append(
            "      <tr><td><a href=\"%s\">%s</a></td><td>%s</td>"
            "<td class=\"num\">%d</td><td>%s</td></tr>"
            % (esc(i["url"]), esc(i["name"]), esc(i["scope"]), i["layers"],
               esc(i["verified"])))
    return "\n".join(rows)


def body(fleet, pages, seats, tabled, tables, gaps, jobs, signal):
    signal_text = ", ".join("%s=%s" % (k, v) for k, v in sorted(signal.items()))
    return """
  <section>
    <p class="lede">districtry answers one question: <strong>which civic districts contain the
      point you picked, and who represents you there.</strong> It is free, needs no account, and
      is built and maintained by one person.</p>
    <p>It began as a Chicago-only explorer and now answers in %(n)d places. Every boundary comes
      from the government that draws it and every name from the body that elects or appoints the
      person, each cited on the card that shows it.</p>
  </section>

  <section>
    <h2>Where it answers</h2>
    <div class="table-wrap">
    <table>
      <thead><tr><th>Place</th><th>Scope</th><th class="num">Layers</th><th>Sources verified</th></tr></thead>
      <tbody>
%(rows)s
      </tbody>
    </table>
    </div>
    <p class="cta-note">Each place has its own sources page listing every layer, what it answers,
      and the publisher its boundary comes from.</p>
  </section>

  <section>
    <h2>What it publishes</h2>
    <ul class="facts">
      <li><strong>%(pages)s</strong> per-county pages naming <strong>%(seats)s</strong> county
        officeholders, one page per county board.</li>
      <li><strong>%(tabled)s</strong> more across the <strong>%(tables)s</strong> rosters
        tabled on its question pages, each one dated with the day it describes.</li>
      <li><strong>%(jobs)s</strong> scheduled jobs that re-read a published source on their own
        timetable. A job that finds a different officeholder opens a pull request rather than
        committing, so nothing about a person ships without someone looking at it first.</li>
      <li><strong>%(gaps)s</strong> recorded data gaps — places where a publisher withholds
        something, written down in the app rather than papered over.</li>
    </ul>
  </section>

  <section>
    <h2>How it decides what to say</h2>
    <p><strong>An officeholder is never guessed.</strong> Where no verifiable roster exists the
      card links the official body instead of inventing a name, and says so. Where two sources
      disagree, the disagreement is recorded rather than resolved by preference.</p>
    <p><strong>A boundary comes from the authority that draws it</strong> — a county GIS, a state
      redistricting filing, the Census Bureau, a clerk's certified election returns. Where a
      boundary had to be derived, the derivation and its checks are written down in the script
      that did it, and that script is public.</p>
    <p><strong>Absence is published.</strong> A county whose board this project cannot name has
      a gap record saying what was tried and what answered, and that record is in the app's own
      data-gaps panel — not only in a document nobody reads.</p>
  </section>

  <section>
    <h2>Corrections</h2>
    <p>If a name, a boundary or a contact detail is wrong, say so and it gets fixed. Every
      correction gets a reply. The fastest route is
      <a href="mailto:corrections@overberg.co?subject=districtry%%20correction">corrections@overberg.co</a>;
      <a href="%(repo)s/issues/new" target="_blank" rel="noopener">an issue on GitHub</a> works
      too, and the whole history of every file is
      <a href="%(repo)s" target="_blank" rel="noopener">there to read</a>.</p>
  </section>

  <section>
    <h2>For machines</h2>
    <p>A short guide for a client reading the site rather than crawling it is at
      <a href="/llms.txt">/llms.txt</a>. <a href="/robots.txt">robots.txt</a> disallows no
      crawler by name and carries <code>Content-Signal: %(signal)s</code>: search is welcome, so
      is grounding an answer in these pages by reference with a link back to the page that names
      the person, and training is reserved. Every fact here comes from a government publisher and
      is cited to it, so there is nothing to withhold and every reason to want the answers found.</p>
  </section>

  <p class="disclaimer"><strong>Not for legal or official use.</strong> Boundary and roster data
    come from public sources that explicitly disclaim legal precision. Confirm a district
    assignment with the relevant government office before relying on it for anything official.</p>
""" % {
        "n": len(fleet),
        "rows": fleet_rows(fleet),
        "pages": "{:,}".format(pages),
        "seats": "{:,}".format(seats),
        "tabled": "{:,}".format(tabled),
        "tables": "{:,}".format(tables),
        "gaps": "{:,}".format(gaps),
        "jobs": "{:,}".format(jobs),
        "repo": REPO_URL,
        "signal": esc(signal_text),
    }


EXTRA_CSS = """
<style>
.facts { margin: 0; padding-left: 1.15rem; display: grid; gap: 0.5rem; }
.facts li { max-width: 68ch; }
</style>
"""


def build():
    fleet = instances()
    pages, seats = county_pages()
    tabled, tables = table_names()
    gaps = recorded_gaps()
    jobs = weekly_jobs()
    signal = content_signal()
    if not signal:
        fail("robots.txt carries no Content-Signal for `*` — the page states it, "
             "so it cannot be written without one")
    # The six instances, and the privacy page. page_consistency_test.mjs
    # requires every page in the sitemap to link it, and the shared shell does
    # not carry that link — privacy.html is exempt from its own rule, so the
    # shell never needed one. This page is the first other user of the shell.
    links = "\n      ".join(
        ['<a href="%s">%s</a>' % (esc(i["url"]), esc(i["name"])) for i in fleet]
        + ['<a href="/privacy.html">Privacy</a>'])
    # render_page runs the whole page through one more % substitution for the
    # shell's own slots, and this body carries none — but it does carry a
    # literal %20 in a mailto. Escaping here keeps it out of that pass rather
    # than writing %%%%20 in the prose and hoping the double escape survives
    # the next edit.
    return render_page(
        pagetitle="About", pagesub=SUB, generator=GENERATOR,
        body=body(fleet, pages, seats, tabled, tables, gaps, jobs,
                  signal).replace("%", "%%"),
        title=TITLE, desc=DESC, jsonld=jsonld(fleet),
        footerlinks=links, canonical=CANONICAL,
    ).replace("</head>", EXTRA_CSS.strip() + "\n</head>", 1), (
        len(fleet), pages, seats, tabled, gaps, jobs)


WORKFLOW_DIR = os.path.join(REPO_ROOT, ".github", "workflows")


def feeding_files():
    """Every file whose CONTENT moves a number on this page.

    Derived from the generators that count them rather than listed here, for
    the reason build_county_pages.check_workflows already gives about filename
    patterns: a list would go stale at the speed the frontier moves, and a
    pattern cannot tell which instance a file belongs to.

    `weekly_jobs()` is deliberately not represented. It counts workflow FILES
    carrying a `schedule:`, so it moves when a workflow is ADDED and never when
    one runs — no refresh can change it, so no refresh owes this page a step
    for it.
    """
    from build_county_pages import INSTANCES, load_instance  # noqa: E402
    from build_officeholder_tables import TABLES, roster_path  # noqa: E402
    feeds = set()
    for inst in INSTANCES:
        for path in load_instance(inst)[3]:
            feeds.add(os.path.relpath(path, REPO_ROOT))
    for entry in TABLES:
        for section in entry["sections"]:
            feeds.add(roster_path(entry["tag"], section["roster"]))
    for path in glob.glob(os.path.join(REPO_ROOT, "*", "data", "app",
                                       "coverage-gaps.json")):
        feeds.add(os.path.relpath(path, REPO_ROOT))
    if len(feeds) < 2:
        fail("feeding_files() found %d input(s), which cannot be right — the "
             "generators it reads have moved and this check is now vacuous"
             % len(feeds))
    return feeds


def check_workflows():
    """A weekly job that rewrites one of those files must regenerate this page.

    THIS PAGE SHIPPED WITHOUT THAT WIRING AND #991 IS WHERE IT SURFACED. The
    page counts the per-county pages and the seats on them, so any run that
    seats or unseats anybody moves a number on it — and on 2026-09-17 the first
    roster PR after the page shipped (#977, two days earlier) went red on
    `--check` for one net name across Buffalo, Green Lake and Marinette. That
    failure lands on a bot's own pull request, which is the worst place to
    discover a convention: nobody wrote the branch, and the number it is wrong
    about is not the number the PR is for.

    Measured on introduction: 102 inputs, and 79 workflows rewriting one of
    them with no step here. The same shape as build_county_pages.py's and
    build_officeholder_tables.py's own checks, and named separately from both
    because this page counts gap records as well as people, so a workflow can
    owe this page a step while owing neither of those one.

    A workflow that stages nothing is a watcher and is not asked to build.
    """
    problems = []
    feeds = feeding_files()
    for path in sorted(glob.glob(os.path.join(WORKFLOW_DIR, "*.yml"))):
        text = open(path, encoding="utf-8").read()
        if "git add " not in text:
            continue                      # a watcher: reads, commits nothing
        rel = os.path.relpath(path, REPO_ROOT)
        hits = sorted(f for f in feeds if f in text)
        if not hits:
            continue
        if "scripts/build_about_page.py" not in text:
            problems.append(
                "%s rewrites %s and never runs scripts/build_about_page.py — "
                "its bot PR would fail this page's own --check on a number the "
                "PR is not about" % (rel, ", ".join(hits[:3])))
        elif "about.html" not in text.split("git add ", 1)[1].split("\n")[0]:
            problems.append(
                "%s regenerates about.html and never stages it — add "
                "`about.html` to its `git add` line" % rel)
    return problems


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="fail on drift rather than writing")
    args = ap.parse_args()

    problems = check_workflows()
    if problems:
        for line in problems:
            print("  - " + line)
        fail("%d weekly workflow(s) rewrite a file this page counts and do not "
             "regenerate it." % len(problems))

    page, (n, pages, seats, tabled, gaps, jobs) = build()
    summary = ("%d place(s), %d county page(s) naming %d, %d more in tables, "
               "%d recorded gap(s), %d scheduled job(s)"
               % (n, pages, seats, tabled, gaps, jobs))
    current = open(PAGE, encoding="utf-8").read() if os.path.exists(PAGE) else None
    if args.check:
        if current is None:
            fail("about.html does not exist. Run `python3 scripts/build_about_page.py`.")
        if current != page:
            for line in list(difflib.unified_diff(
                    current.split("\n"), page.split("\n"), "shipped", "built",
                    lineterm="", n=1))[:12]:
                print("  " + line)
            fail("about.html has drifted from the tree it describes. Every number "
                 "on it is read at build time, so regenerate rather than editing "
                 "the claim.")
        print("build-about-page: OK — current; %s" % summary)
        return
    if current == page:
        print("build-about-page: OK — no change; %s" % summary)
        return
    with open(PAGE, "w", encoding="utf-8") as f:
        f.write(page)
    print("build-about-page: wrote about.html — %s" % summary)


if __name__ == "__main__":
    main()
