#!/usr/bin/env python3
"""Fetch Search Console performance for every property this credential can see,
and write data/search-performance.json.

WHY THIS IS A WORKFLOW STEP AND NOT PART OF THE REPORT BUILD. The traffic
report is assembled outside this repo, from a session that has no access to
GOOGLE_SA_KEY — an Actions secret is write-only and exists only inside a job.
So the fetch runs here, commits its result, and the report reads the committed
file. The JSON is the handoff between the place that holds the credential and
the place that draws the chart.

PROPERTIES ARE DISCOVERED, NEVER HARDCODED. districtry renamed on 2026-08-24
and Search Console data belongs to a PROPERTY, so the history is split across
two: chidistricts.com (from 2026-07-12) and districtry.com (from 2026-08-23).
Measured 2026-09-08, THEY OVERLAP rather than hand over — the old domain still
surfaces in results and 301s across, because Google migrates an index
gradually. Both keep accruing impressions, so a build that assumed a clean
cutover would drop fifteen days from one side or double-count them as one
series. sites.list is asked every run instead; a third property appearing (or
one losing its grant) shows up as a change in this file rather than as a
silently short chart.

WHAT IS NOT COLLECTED: nothing per-person, because Search Console has nothing
per-person to give. Rows are aggregate query/page/device counts, and Google
already withholds rare queries that could identify an individual searcher —
which is also why the clicks and impressions here will not reconcile exactly
with the totals shown in the Search Console UI, and why the report says so
rather than quietly presenting a subset as the whole.
"""

import datetime
import json
import os
import sys
import urllib.parse

import requests
from google.auth.transport.requests import Request
from google.oauth2 import service_account

API = "https://searchconsole.googleapis.com/webmasters/v3"
SCOPES = ["https://www.googleapis.com/auth/webmasters.readonly"]
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "data", "search-performance.json")

# Before the site existed (launch 2026-07-10), so the API clamps to whatever
# each property actually holds and the start date is measured, not assumed.
START = "2026-06-01"
PAGE = 25000          # the API's own per-request ceiling
MAX_ROWS = 100000     # sanity stop; this site is nowhere near it

# A property returning nothing is usually a revoked grant rather than a quiet
# week, and writing that would silently empty the report's search card.
MIN_IMPRESSIONS = 1


def credentials():
    raw = os.environ.get("GOOGLE_SA_KEY", "").strip()
    if not raw:
        sys.exit("GOOGLE_SA_KEY is unset — this must run where the secret is "
                 "mounted (see .github/workflows/update-search-performance.yml).")
    creds = service_account.Credentials.from_service_account_info(
        json.loads(raw), scopes=SCOPES)
    creds.refresh(Request())
    return creds


def post(headers, site_url, body):
    """One searchAnalytics/query, paged through startRow."""
    url = "%s/sites/%s/searchAnalytics/query" % (
        API, urllib.parse.quote(site_url, safe=""))
    rows, start = [], 0
    while start < MAX_ROWS:
        payload = dict(body, rowLimit=PAGE, startRow=start)
        r = requests.post(url, headers=headers, json=payload, timeout=120)
        if r.status_code != 200:
            sys.exit("%s: HTTP %d from searchAnalytics — %s"
                     % (site_url, r.status_code, r.text[:300]))
        got = r.json().get("rows", [])
        rows.extend(got)
        if len(got) < PAGE:      # short page means the last one
            break
        start += PAGE
    return rows


def series(rows, key="keys"):
    return [{"key": r[key][0],
             "clicks": r.get("clicks", 0),
             "impressions": r.get("impressions", 0),
             "ctr": round(r.get("ctr", 0.0), 6),
             "position": round(r.get("position", 0.0), 2)}
            for r in rows]


def main():
    creds = credentials()
    headers = {"Authorization": "Bearer %s" % creds.token}
    end = (datetime.date.today() - datetime.timedelta(days=1)).isoformat()

    r = requests.get("%s/sites" % API, headers=headers, timeout=60)
    if r.status_code != 200:
        sys.exit("sites.list: HTTP %d — %s" % (r.status_code, r.text[:300]))
    sites = [e["siteUrl"] for e in r.json().get("siteEntry", [])
             if e.get("permissionLevel") != "siteUnverifiedUser"]
    if not sites:
        sys.exit("no Search Console properties visible to this service "
                 "account. Add its e-mail as a user on the property — Search "
                 "Console permissions are separate from GCP IAM.")

    out = {
        "_comment": ("Generated by scripts/gsc_fetch.py from the Search Console "
                     "Search Analytics API. Properties are discovered per run, "
                     "not hardcoded: this site renamed on 2026-08-24 and the two "
                     "properties OVERLAP rather than hand over, because the old "
                     "domain still surfaces in results and redirects across."),
        "fetched": datetime.datetime.now(datetime.timezone.utc)
                           .strftime("%Y-%m-%dT%H:%M:%SZ"),
        "window": {"start": START, "end": end},
        "properties": {},
    }
    window = {"startDate": START, "endDate": end}
    total_impressions = 0

    for site in sorted(sites):
        print("fetching %s" % site)
        by_date = post(headers, site, dict(window, dimensions=["date"]))
        if not by_date:
            print("  no data in window")
            out["properties"][site] = {"days": [], "queries": [], "pages": [],
                                       "clicks": 0, "impressions": 0}
            continue
        queries = post(headers, site, dict(window, dimensions=["query"]))
        pages = post(headers, site, dict(window, dimensions=["page"]))
        clicks = sum(r.get("clicks", 0) for r in by_date)
        impressions = sum(r.get("impressions", 0) for r in by_date)
        total_impressions += impressions
        days = sorted(r["keys"][0] for r in by_date)
        print("  %s..%s  %d days, %d clicks, %d impressions, %d queries"
              % (days[0], days[-1], len(days), clicks, impressions, len(queries)))
        out["properties"][site] = {
            "first_date": days[0], "last_date": days[-1],
            "clicks": clicks, "impressions": impressions,
            "days": series(by_date),
            # Ranked by impressions, not clicks: with 120 clicks across the
            # whole fleet history a clicks sort returns one real row and then
            # ties, while impressions is where the signal is (find my district
            # sits at 303 impressions against 2 clicks).
            "queries": sorted(series(queries),
                              key=lambda x: -x["impressions"])[:500],
            "pages": sorted(series(pages), key=lambda x: -x["impressions"]),
        }

    if total_impressions < MIN_IMPRESSIONS:
        sys.exit("refusing to write: %d impressions across %d property(ies). "
                 "That is a revoked grant or an API change, not a quiet week."
                 % (total_impressions, len(sites)))

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=1, sort_keys=False)
        f.write("\n")
    print("wrote %s — %d property(ies), %d impressions"
          % (os.path.relpath(OUT), len(sites), total_impressions))


if __name__ == "__main__":
    main()
