#!/usr/bin/env python3
"""
Scrape Rock Island County's clerk Elected Officials listing into the payload
build_municipal_officials_roster.py consumes.

SOURCE. The County Clerk's "Elected Officials by Jurisdiction" PDF (Document
Center id 291, regenerated by the clerk's election system — the edition date
rides the page footer) lists every one of the county's fifteen municipalities
with its FULL governing body: head of government, clerk, treasurer and every
trustee / ward alderman, each with party, elected date, TERM-UP year and,
for many, a direct phone. Moline, East Moline and Rock Island elect aldermen
by ward. This is the county's own certified officeholder record — the same
depth as Cook's DOEO API, from a PDF.

FETCH POSTURE: open. Plain `requests` with a browser UA gets the PDF at a
stable DocumentCenter URL.

RECORD SHAPE (one official), in the order the clerk's PDF actually prints it:
a party line (optionally led by a phone, and reading "Appointed" in the party
position for appointed officers), the official's HOME address (never
collected), a blank, THE NAME, an office caption that PERSISTS across the
following records (trustee blocks print it once), the Appointed:/Elected/
Term Up: label rows, and two value rows (elected date + term year, or
"Appointed" twice) which close the record.

THE NAME'S POSITION IS THE WHOLE OF THIS PARSER'S HISTORY. It was read as the
line AFTER the two value rows until 2026-09-19, which is the line that opens
the NEXT record — so from the 2026-09-04 refresh, when the clerk republished
with this layout, every one of Rock Island's 112 officials shipped named after
their successor's party line ("(309) 798-5353 Appointed", "NP", "Democratic"),
and the last official on each page took the page footer, whose page number
fuses onto the edition date ("78/28/2026"). It was live for fifteen days. The
name is now taken where it is printed, and build_municipal_officials_roster.py
refuses any value of those three shapes for every county, so a future layout
change fails the build instead of inventing officeholders. The parser is a
state machine over that stream; a jurisdiction caption ("Andalusia Village",
"East Moline City") switches municipalities, and any OTHER jurisdiction
caption (township, school board…) closes the municipal context so nothing
downstream is misattributed.

An office caption ending in * (Clerk*, Treasurer*) and a value row of
"Appointed" both mark appointment; either ships appointed=True — the card
must not imply an election that did not happen.

Usage:
    python3 rock_island_municipal_officials_scraper.py --out rock_island_municipal_officials.json
"""

import argparse
import datetime
import io
import json
import re
import sys

import requests
from scraper_common import UA_CHROME_WIN_126  # noqa: E402  (shared machinery — do not fork)

try:
    import pypdf
except ImportError:  # pragma: no cover
    pypdf = None

PDF_URL = ("https://rockislandcountyil.gov/DocumentCenter/View/291/"
           "Elected-Officials-Listing-PDF")
OFFICIALS_PAGE = "https://rockislandcountyil.gov/236/County-Clerk"
HEADERS = {
    "User-Agent": UA_CHROME_WIN_126,
}
REQUEST_TIMEOUT = 120

BANNER_RE = re.compile(r"^ROCK ISLAND COUNTY\s+-\s+ELECTED OFFICIALS", re.I)
MUNI_RE = re.compile(r"^([A-Z][A-Za-z .'’-]+?)\s+(Village|City)$")
# Any other jurisdiction caption ends the municipal context ("Blackhawk Twp"
# follows Silvis, then fire/school/library districts).
OTHER_JURISDICTION_RE = re.compile(
    r"^[A-Z][A-Za-z .'’#\d-]+\s+(Twp\.?|Township|Dist\.?|District|Board|Library|"
    r"Park|Fire|Sanitary|Airport|College|Cemetery|Road|Authority|Commission|"
    r"Comm\.?|Preserve)\s*(#\s*\d+)?$")
OFFICE_RE = re.compile(r"^(President|Mayor|Clerk/Treasurer\*?|Clerk\*?|Treasurer\*?|"
                       r"Trustee\*?|Ald\.?\s*Ward\s*(\d+)|Alderman(?:\s+Ward\s*(\d+))?)\s*$")
# A record OPENS on its party line: an optional phone (the clerk prints both
# "(309) 798-5353" and "309-269-7499" forms) followed by the party as one to
# three capitalized words ("NP", "Indep. Party", "Citizens", "Appointed" for
# appointed officers). Never digits after the phone — that shape is a home
# address, which only occurs inside an open record and is ignored there.
PARTY_RE = re.compile(r"^(?:\(?(\d{3})\)?[ .-]+(\d{3})[ .-]+(\d{4})\s+)?"
                      r"([A-Z][A-Za-z.'&-]*(?:\s+[A-Z][A-Za-z.'&-]*){0,2})$")
LABEL_RE = re.compile(r"^(Appointed:|Elected|Term Up:)\s*$")
# A VACANT seat prints no address and no separate value rows: its term year is
# FUSED onto its own label ("Term Up: 2027"), so the record never reaches the
# two values that close one. Left unhandled it stays open and swallows the next
# official outright — Silvis's Ald Ward 1 vacancy ate Chad J. Vroman, and Oak
# Grove's Trustee vacancy ate two trustees. The fused row closes the record.
TERM_UP_INLINE_RE = re.compile(r"^Term Up:\s*(20\d{2})$")
# The home address sits between the party line and the name and is NEVER
# collected. It is matched on a street number OR the state abbreviation,
# because the clerk prints partial addresses too — Hampton's Clerk carries
# "  Hampton  IL  " with no number and no ZIP, and a rule keyed on either of
# those reads it as a person and then discards the real name on the next line.
# Measured against all 4,327 names in the pre-break roster fleet-wide: none
# starts with a digit and none contains IL as a word, so this cannot eat a name.
ADDRESS_RE = re.compile(r"^\d|\bIL\b")   # applied with .search(), not .match():
# the state abbreviation sits at the END of the line, so an anchored read sees
# only the street-number alternative and lets "Hampton IL" through as a person.
# Real months only: the page footer fuses the page number onto the edition
# date ("75/13/2026" = page 7 + 5/13/2026) and must never read as a value.
VALUE_RE = re.compile(r"^((0[1-9]|1[0-2])/([0-2]\d|3[01])/\d{4}|"
                      r"(0[1-9]|1[0-2])/\d{4}|20\d{2}|Appointed)$")

HEAD_TITLES = {"mayor", "president"}
NON_PERSON_NAMES = {"vacant", "vacancy", "unassigned", "open", "tbd", "none", "n/a"}

MIN_MUNICIPALITIES = 13
MIN_OFFICIALS = 100
MIN_HEADS = 13
MIN_WARD_SEATS = 18


def clean(value):
    value = re.sub(r"\s+", " ", (value or "")).strip().strip(",")
    return value or None


def fetch_pdf(url):
    resp = requests.get(url, headers=HEADERS, timeout=REQUEST_TIMEOUT)
    resp.raise_for_status()
    if not resp.content.startswith(b"%PDF"):
        raise RuntimeError("clerk listing URL did not return a PDF (got %d bytes of %s)"
                           % (len(resp.content), resp.headers.get("Content-Type")))
    return resp.content


def parse(pdf_bytes, warnings):
    if pypdf is None:
        raise RuntimeError("pypdf is required (pip install -c scripts/requirements.txt pypdf)")
    reader = pypdf.PdfReader(io.BytesIO(pdf_bytes))
    lines = []
    for page in reader.pages:
        lines.extend(l.strip() for l in (page.extract_text() or "").split("\n"))

    officials = []
    municipalities = []
    muni = None            # "Village of Andalusia"
    office = None          # (title, district, office_appointed)
    record = None          # {phone, party_appointed, values: []}

    def close_record(name_line):
        nonlocal record
        if record is None or office is None or muni is None:
            record = None
            return
        name = clean(name_line)
        if not name or name.lower() in NON_PERSON_NAMES:
            if name:
                warnings.append("dropped a %s seat published as '%s' in %s"
                                % (office[0], name, muni))
            record = None
            return
        rec = {"jurisdiction": muni, "office": office[0], "district": office[1],
               "name": name, "source_url": PDF_URL}
        values = record["values"]
        appointed = office[2] or record["party_appointed"] or "Appointed" in values
        years = [v for v in values if re.fullmatch(r"\d{4}", v)]
        if years:
            rec["term_expires"] = years[-1]
        if appointed:
            rec["appointed"] = True
        if record["phone"]:
            rec["person_phone"] = record["phone"]
        officials.append(rec)
        record = None

    for raw in lines:
        line = clean(raw)
        if not line or BANNER_RE.match(line):
            continue
        m = MUNI_RE.match(line)
        if m:
            name = "%s of %s" % (m.group(2), m.group(1))
            if muni != name:
                if OTHER_JURISDICTION_RE.match(line):
                    pass
                muni = name
                if name not in municipalities:
                    municipalities.append(name)
            office = None
            record = None
            continue
        if OTHER_JURISDICTION_RE.match(line):
            muni = None
            office = None
            record = None
            continue
        if muni is None:
            continue
        om = OFFICE_RE.match(line)
        if om:
            title = om.group(1)
            ward = om.group(2) or om.group(3)
            office_appointed = title.endswith("*")
            base = title.rstrip("*")
            if base.lower().startswith("ald"):
                base = "Alderman"
            office = (base, ("Ward %d" % int(ward)) if ward else None, office_appointed)
            continue
        tm = TERM_UP_INLINE_RE.match(line) if record is not None else None
        if tm:
            record["values"].append(tm.group(1))
            close_record(record["name"])
            continue
        if LABEL_RE.match(line):
            continue
        # Order matters: an open record's value rows can read "Appointed",
        # which the party pattern also matches — inside a record the value
        # interpretation wins, else every appointed officer restarts their
        # own record and loses their name.
        if record is not None and VALUE_RE.match(line):
            record["values"].append(line)
            if len(record["values"]) == 2:
                # The record closes on its second value row. The name was read
                # four lines back, where the clerk prints it; a record that
                # reached here without one is a layout this parser does not
                # understand, and close_record drops it rather than reaching
                # for whatever line comes next.
                close_record(record["name"])
            continue
        if record is not None and record["name"] is None and not ADDRESS_RE.search(line):
            # Party line, home address, blank, NAME. Anything inside an open
            # record that is not the address and not one of the structural rows
            # above is the name, and only the FIRST such line is taken.
            record["name"] = line
            continue
        pm = PARTY_RE.match(line) if record is None else None
        if pm:
            phone = ("%s-%s-%s" % (pm.group(1), pm.group(2), pm.group(3))
                     if pm.group(1) else None)
            record = {"phone": phone,
                      "party_appointed": pm.group(4) == "Appointed",
                      "name": None,
                      "values": []}
            continue
        # everything else (home addresses, blanks) is deliberately ignored
    return municipalities, officials


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True)
    parser.add_argument("--pdf", help="parse a local copy instead of fetching")
    args = parser.parse_args()

    warnings = []
    try:
        pdf_bytes = open(args.pdf, "rb").read() if args.pdf else fetch_pdf(PDF_URL)
        municipalities, officials = parse(pdf_bytes, warnings)
    except Exception as exc:  # noqa: BLE001
        print("FATAL: %s" % exc, file=sys.stderr)
        sys.exit(1)

    for warning in sorted(set(warnings)):
        print("  warning: %s" % warning, file=sys.stderr)

    heads = sum(1 for p in officials if p["office"].lower() in HEAD_TITLES)
    seats = sum(1 for p in officials if p.get("district"))
    problems = []
    if len(municipalities) < MIN_MUNICIPALITIES:
        problems.append("%d municipalities < floor %d" % (len(municipalities), MIN_MUNICIPALITIES))
    if len(officials) < MIN_OFFICIALS:
        problems.append("%d officials < floor %d" % (len(officials), MIN_OFFICIALS))
    if heads < MIN_HEADS:
        problems.append("%d heads of government < floor %d" % (heads, MIN_HEADS))
    # Moline's, East Moline's and Rock Island's ward-alderman rows are the
    # part of this payload the municipal-ward layer joins to.
    if seats < MIN_WARD_SEATS:
        problems.append("%d ward seats < floor %d" % (seats, MIN_WARD_SEATS))
    if problems:
        for problem in problems:
            print("  FAIL: %s" % problem, file=sys.stderr)
        print("FATAL: refusing to write a payload that lost coverage", file=sys.stderr)
        sys.exit(1)

    scraped_at = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    for record in officials:
        record["scraped_at"] = scraped_at
    payload = {
        "county": "Rock Island",
        "directory_url": PDF_URL,
        "officials_page": OFFICIALS_PAGE,
        "scraped_at": scraped_at,
        "municipalities": [{"name": n, "source_url": PDF_URL,
                            "scraped_at": scraped_at} for n in municipalities],
        "officials": officials,
    }
    with open(args.out, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)
    print("scraped %d municipalities, %d officials (%d heads, %d ward seats) -> %s"
          % (len(municipalities), len(officials), heads, seats, args.out), file=sys.stderr)


if __name__ == "__main__":
    main()
